### PR TITLE
Add ORT to the list of adopters

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by jkowalleck** [comment]
this PR mixes multiple scopes in one PR:
- reformat/alter the "Known implementations" section
- reformat/alter the "Users, adopters and links" section
- add something to the  "Users, adopters and links" section.

Some changes may be easy to adopt, others are debatable.

Please create a dedicated PR for each scoped change, @sschuberth.
Thank you in advance.

I will close this PR without merging.

**Comment by sschuberth** [comment]
> this PR mixes multiple scopes in one PR:

True, but it nicely separates these (tiny) scopes into separate commits.

> Please create a dedicated PR for each scoped change, @sschuberth.

Seems like overkill to me for such trivial changes. But if you really feel like these trivial changes are each debatable on their own, I'll create individual PRs.

> I will close this PR without merging.

Honestly, I think that's a bit harsh without having written out contribution guidelines for this repository. I could have as well adapted this PR by rewriting commit history, which would have been my preferred approach.

**Comment by sschuberth** [comment]
> I'll create individual PRs.

Here you go for now:
- https://github.com/package-url/purl-spec/pull/352
- https://github.com/package-url/purl-spec/pull/353

The other change makes only sense as-is after these (or at least the latter) is merged.

**Comment by jkowalleck** [comment]
I totally understand you, @sschuberth .

My reasoning is: 
there are a lot of unmerged PRs here, for the sole reason that they require communication, back and forth, and such.
I wanted to have your changes moving faster that the usual PRs here, since they all made a lot of sense to me. People would probably find it hard to review or would nitpick here and there - which would have as lowed reviews down. Individual changes as separate PRs - they may move with individual speed, and one does not block the other.

**Comment by sschuberth** [comment]
> The other change makes only sense as-is after these (or at least the latter) is merged.

See https://github.com/package-url/purl-spec/pull/354.

**Pull request closed without merging**
