### PR TITLE
Fix casing: semver -> SemVer; nevra -> NEVRA

### PR DESCRIPTION
**Pull request by bact**
Use casing according to official document
- https://semver.org/
- https://docs.fedoraproject.org/en-US/modularity/core-concepts/nsvca/

### CODE REVIEW

**Review by santosomar — APPROVED** [review]
Self-explanatory and editorial.

**Comment by johnmhoran** [comment]
Thank you @bact -- this looks good.  Since this branch is out of date with `master`, can you please merge the latest `master` into your branch, fix any conflicts, and update your PR?  I can then go ahead and merge.

**Review by johnmhoran — APPROVED** [review]
Thank you @bact -- LGTM!

**Comment by bact** [comment]
@johnmhoran Thank you. I do the follow up a bit here: #341

**Pull request merged**
